# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-21 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='Empty Comment'),
            preserve_default=False,
        ),
    ]
