# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-21 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_application', '0002_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_on_message', to='the_wall_application.Message'),
        ),
    ]
